---
- name: Install redshift
  when: ansible_facts.pkg_mgr == "apt"
  become: yes
  become_method: sudo
  apt:
    pkg:
      - redshift-gtk
    state: latest

- name: Symlink redshift config file
  when: ansible_facts.pkg_mgr == "apt"
  file:
    src: "{{ role_path }}/files/redshift.conf"
    dest: "{{ ansible_facts.user_dir }}/.config/redshift.conf"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link
  
- name: Autostart Redshift - Xubuntu
  when: ansible_facts.env.DESKTOP_SESSION == "xubuntu"
  copy:
    src: "{{ role_path }}/files/Redshift.xfce"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/redshift.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Autostart Redshift - Cinnamon
  when: ansible_facts.env.DESKTOP_SESSION == "cinnamon"
  copy:
    src: "{{ role_path }}/files/Redshift.xfce"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/redshift.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Autostart Redshift - Ubuntu
  when: ansible_facts.env.DESKTOP_SESSION == "ubuntu"
  copy:
    src: "{{ role_path }}/files/Redshift.gnome"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/redshift.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Autostart Redshift - Kubuntu
  when: ansible_facts.env.DESKTOP_SESSION == "plasma"
  copy:
    src: "{{ role_path }}/files/Redshift.gnome"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/redshift.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Fix autostart command
  # Template uses '$HOME' which is not valid inside of a desktop file
  when: ansible_facts.distribution == "Ubuntu"
  replace:
    path: "{{ ansible_facts.user_dir }}/.config/autostart/redshift.desktop"
    regexp: '\$HOME'
    replace: "{{ ansible_facts.user_dir }}"
