---
- name: Install Redshift GTK - APT
  when: ansible_facts.pkg_mgr == "apt"
  become: yes
  become_method: sudo
  apt:
    pkg:
      - redshift-gtk
    state: latest

- name: Symlink redshift config file
  when: ansible_facts.pkg_mgr == "apt"
  copy:
    src: "{{ role_path }}/files/redshift.conf"
    dest: "{{ ansible_facts.user_dir }}/.config/redshift.conf"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
  
- name: Autostart Redshift - XFCE
  when: ansible_facts.env.DESKTOP_SESSION in ["xubuntu", "xfce"]
  vars:
    user_home: "{{ ansible_facts.user_dir }}"
  template:
    src: "{{ role_path }}/files/Redshift.xfce.j2"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/redshift.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Autostart Redshift - Ubuntu
  when: ansible_facts.env.DESKTOP_SESSION in ["ubuntu", "cinnamon", "plasma"]
  vars:
    user_home: "{{ ansible_facts.user_dir }}"
  template:
    src: "{{ role_path }}/files/Redshift.gnome.j2"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/redshift.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
