---
- name: Install redshift - (X)Ubuntu
  when: ansible_facts.distribution == "Ubuntu"
  become: yes
  become_method: sudo
  apt:
    pkg:
      - redshift-gtk
    state: latest

- name: Symlink redshift config file
  when: ansible_facts.distribution == "Ubuntu"
  file:
    src: "{{ role_path }}/files/redshift.conf"
    dest: "{{ ansible_facts.user_dir }}/.config/redshift.conf"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link

- name: Autostart Redshift
  when: ansible_facts.distribution == "Ubuntu"
  copy:
    src: "{{ role_path }}/files/Redshift.template"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/Redshift.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
  
- name: Fix autostart command
  # Template uses '$HOME' which is not valid inside of a desktop file
  when: ansible_facts.distribution == "Ubuntu"
  replace:
    path: "{{ ansible_facts.user_dir }}/.config/autostart/Redshift.desktop"
    regexp: '\$HOME'
    replace: "{{ ansible_facts.user_dir }}"
