---
# - name: Debug
#   debug: var=ansible_facts

# - name: Role
#   debug: var=role_path

- name: Symlink Bash Profile
  file:
    src: "{{ role_path }}/files/bash_profile"
    dest: "{{ ansible_facts.user_dir }}/.bash_profile"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link