---
- name: Configure Ubuntu
  hosts: localhost
  vars:
    # https://github.com/ansible/ansible/issues/14468 
    ansible_python_interpreter: /usr/bin/python3
    storable_device: false
    asdf_plugins:
      - "ruby"
      - "nodejs"
      - "python"
  roles:
    - asdf
    - bash
    - git
    - keyboard
    - libinput
    - mouse
    - redshift
    - tmux 
    - vim

