---
- name: Configure Linux System
  hosts: localhost
  vars:
    # https://github.com/ansible/ansible/issues/14468 
    ansible_python_interpreter: /usr/bin/python3
    work_device: false
    asdf_plugins:
      - "ruby"
      - "nodejs"
      - "python"
      - "argocd"
      - "awscli"
      - "gcloud"
      - "golang"
      - "helm"
      - "k9s"
      - "kubectl"
      - "kubectx"
      - "vault"
  roles:
    - asdf
    - bash
    # - docker
    - git
    - keyboard
    - podman
    - redshift
    - tmux 
    - vim
