---
- name: Configure Linux System
  hosts: localhost
  vars:
    work_device: false
    asdf_plugins:
      - "ruby"
      - "nodejs"
      - "python"
      - "argocd"
      - "awscli"
      - "gcloud"
      - "golang"
      - "helm"
      - "k9s"
      - "kubectl"
      - "kubectx"
      - "vault"
  roles:
    - apt
    - asdf
    - bash
    # - docker
    - keyboard
    - git
    - podman
    # - redshift
    - tmux 
    - vim
