---
- name: Configure MacOS
  hosts: localhost
  vars:
    asdf_plugins:
      - "argocd"
      - "awscli"
      - "dotnet-core"
      - "gcloud"
      - "golang"
      - "helm"
      - "k9s"
      # - "kpack-cli"
      - "kubectl"
      - "kubectx"
      - "nodejs"
      - "php"
      - "python"
      - "ruby"
      - "rust"
      - "snyk"
      - "terraform"
      - "vault"
    work_device: true
  roles:
    # - asdf
    # - bash
    # - docker
    # - git
    - mise-en-place
    # - tmux
    # - vim
