---
- name: Configure MacOS
  hosts: localhost
  vars:
    asdf_plugins:
      - "awscli"
      - "dotnet-core"
      - "gcloud"
      - "golang"
      - "helm"
      - "kubectl"
      - "kubectx"
      - "nodejs"
      - "python"
      - "ruby"
      - "terraform"
  roles:
    - asdf
    - bash
    - tmux
    - vim

