---
- name: Configure MacOS
  hosts: localhost
  vars:
    asdf_plugins:
      - "awscli"
      - "nodejs"
      - "python"
      - "terraform"
      - "terraform-docs"
    work_device: true
  roles:
    - brew
    - asdf
    - bash
    # - docker
    - git
    - tmux
    - vim
