syntax on

" Vim-Plug Plugin Manager.
" call plug#begin('~/.vim/extensions')
"       Plug 'airblade/vim-gitgutter'
"       Plug 'bling/vim-airline'
"       Plug 'tpope/vim-surround'
"       Plug 'tpope/vim-commentary'
"       Plug 'vim-syntastic/syntastic'
"       Plug 'fatih/vim-go'
" call plug#end()

" set autoindent
set number
set numberwidth=3

" Set Ruler
set colorcolumn=79
highlight ColorColumn ctermbg=233 

set showcmd
set showmode
set backspace=indent,eol,start

" Key remapping
:imap jj <Esc>

" Set TAB to 2 Spaces
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab

" Remove '^G' from beginning of files on Mac using NerdTree:
let g:NERDTreeNodeDelimiter = "\u00a0"

" Syntastic Linter Settings
" https://github.com/vim-syntastic/syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map = { 'passive_filetypes': ['xml'] }
let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_go_checkers = ["go"]
" Use '\sc' to check syntax
nmap <leader>sc :SyntasticCheck<CR> 

" Avro Schema (.avsc) files are JSON
autocmd BufRead,BufNewFile *.avsc setlocal filetype=json

" Golang
let g:go_def_mode="gopls"
let g:go_info_mode="gopls"

