#
# Installs config for Logitech M720 Triathalon Mouse
# Only set for Xubuntu as I'm not sure if Ubuntu needs this
# configuration as well.
#
---
- name: Install Mouse xbindkeys packages - X/Ubuntu
  # when: ansible_facts.env.DESKTOP_SESSION == "xubuntu"
  when: ansible_facts.distribution == "Ubuntu"
  become: yes
  become_method: sudo
  apt:
    pkg:
      - xbindkeys
      - xdotool
    state: latest

- name: Install Xbindkeys.desktop file - X/Ubuntu
  # when: ansible_facts.env.DESKTOP_SESSION == "xubuntu"
  when: ansible_facts.distribution == "Ubuntu"
  copy:
    src: "{{ role_path }}/files/Xbindkeys.desktop"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/Xbindkeys.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Install xbindkeysrc config file - X/Ubuntu
  # when: ansible_facts.env.DESKTOP_SESSION == "xubuntu"
  when: ansible_facts.distribution == "Ubuntu"
  copy:
    src: "{{ role_path }}/files/xbindkeysrc"
    dest: "{{ ansible_facts.user_dir }}/.xbindkeysrc"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
