#
# Run `xev` in terminal, then find the `keycode` of the event
#
# Logitech M720 Triathalon:
#   Button 8 => Side button backwards
#   Button 9 => Side button forward
#   Keycode 37 => Bottom Thumb 
#
---
- name: Austostart Directory
  when: ansible_facts.distribution == "Ubuntu"
  file:
    path: "{{ ansible_facts.user_dir }}/.config/autostart"
    state: directory

- name: Install Mouse xbindkeys packages - All Ubuntu's
  when: ansible_facts.distribution == "Ubuntu"
  become: yes
  become_method: sudo
  apt:
    pkg:
      - xbindkeys
      - xdotool
    state: latest

- name: Install Xbindkeys.desktop file - All Ubuntu's
  when: ansible_facts.distribution == "Ubuntu"
  copy:
    src: "{{ role_path }}/files/Xbindkeys.desktop"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/Xbindkeys.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Install xbindkeysrc config file - All Ubuntu's
  when: ansible_facts.distribution == "Ubuntu"
  copy:
    src: "{{ role_path }}/files/xbindkeysrc"
    dest: "{{ ansible_facts.user_dir }}/.xbindkeysrc"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
