---
- name: Install ASDF Prerequisites - APT
  when: ansible_facts.pkg_mgr == "apt" 
  become: yes
  become_method: sudo
  apt:
    pkg:
      - build-essential
      - curl
      - gcc
      - git
      - gpg
      - dirmngr
      - make
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libpq-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - llvm
      - tk-dev
      - xz-utils
      - zlib1g-dev
      - wget
    state: latest

# TODO: Install ASDF on Linux

- name: Install ASDF - MacOS
  when: ansible_facts.distribution == "MacOSX"
  with_items:
    - asdf
  homebrew:
    name: "{{ item }}"
    state: present

- name: Check Installed Plugins
  ignore_errors: yes
  with_items: "{{ asdf_plugins }}"
  stat:
    path: "{{ ansible_facts.user_dir }}/.asdf/plugins/{{ item }}"
  register: asdf_plugins_installed

- name: Install missing ASDF plugins
  with_items: "{{ asdf_plugins_installed.results }}"
  when: item.stat.exists is false
  command: "asdf plugin add {{ item.item }}"
