---
- name: Install Mise - MacOS
  when: ansible_facts.distribution == "MacOSX"
  with_items:
    - mise
  homebrew:
    name: "{{ item }}"
    state: present

- name: Get latest Mise Releases
  when: ansible_facts.system in ["Linux"]
  uri:
    url: https://api.github.com/repos/jdx/mise/releases/latest
    return_content: true
  register: mise_latest_release

- name: Set mise facts
  when: ansible_facts.system in ["Linux"]
  set_fact:
    latest_tag: "{{ mise_latest_release.json.tag_name }}"
    bin_dir: "/usr/local/bin"

- name: Download latest version - Linux
  when: ansible_facts.system in ["Linux"]
  become: yes
  become_method: sudo
  ansible.builtin.get_url:
    url: "https://github.com/jdx/mise/releases/download/{{ latest_tag }}/mise-{{ latest_tag }}-linux-x64"
    dest: "{{ bin_dir }}/mise"
    mode: '0755'

- name: Ensure mise config path exists
  file:
    path: "{{ ansible_facts.user_dir }}/.config/mise"
    state: directory

- name: Symlink main tool versions
  file:
    src: "{{ role_path }}/files/config.toml"
    dest: "{{ ansible_facts.user_dir }}/.config/mise/config.toml"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link
    force: yes
