--- 
- name: Check if Homebrew is already installed
  when: ansible_facts.distribution == "MacOSX"
  stat:
    path: /usr/local/bin/brew
  register: b

- name: Install Homebrew
  when: not b.stat.exists
  become: yes
  become_method: sudo
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"