---
- name: Install Flameshot - MacOS
  when: ansible_facts.distribution == "MacOSX"
  with_items:
    - flameshot
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present

- name: Install Flameshot - Linux
  when: ansible_facts.system in ["Linux"]
  become: yes
  become_method: sudo
  with_items:
    - flameshot
  package:
    name: "{{ item }}"
    state: latest
