---
- name: Austostart Directory
  file:
    path: "{{ ansible_facts.user_dir }}/.config/autostart"
    state: directory

- name: Autostart Keyboard Settings - Ubuntu (Gnome)
  when: (ansible_facts.env.DESKTOP_SESSION == "ubuntu") or (ansible_facts.env.DESKTOP_SESSION == "budgie-desktop") or (ansible_facts.distribution == "Kali")
  copy:
    src: "{{ role_path }}/files/keyboard_caps_is_ctrl.desktop.gnome"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/setxkbmap.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
  
- name: Autostart Keyboard Settings - XFCE
  when: ansible_facts.env.DESKTOP_SESSION == "xubuntu"
  copy:
    src: "{{ role_path }}/files/keyboard_caps_is_ctrl.desktop.xfce"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/setxkbmap.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Install kb script
  when: ansible_facts.distribution == "Ubuntu"
  become: yes
  become_method: sudo
  copy:
    src: "{{ role_path }}/files/kb"
    dest: "/usr/local/bin"
    mode: 0755
    
