---
- name: Austostart Directory
  file:
    path: "{{ ansible_facts.user_dir }}/.config/autostart"
    state: directory

- name: Autostart Keyboard Settings - Ubuntu (Gnome)
  when: ansible_facts.env.DESKTOP_SESSION in ["ubuntu", "budgie-desktop", "cinnamon"]
  copy:
    src: "{{ role_path }}/files/keyboard_caps_is_ctrl.desktop.gnome"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/setxkbmap.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
  
- name: Autostart Keyboard Settings - XFCE
  when: ansible_facts.env.DESKTOP_SESSION in ["xubuntu", "xfce"]
  copy:
    src: "{{ role_path }}/files/keyboard_caps_is_ctrl.desktop.xfce"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/setxkbmap.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"

- name: Install kb script
  when: ansible_facts.distribution_file_variety in ["Ubuntu", "Debian"]
  become: yes
  become_method: sudo
  copy:
    src: "{{ role_path }}/files/kb"
    dest: "/usr/local/bin"
    mode: 0755
    
- name: Symlink Xmodmap
  file:
    src: "{{ role_path }}/files/xmodmap"
    dest: "{{ ansible_facts.user_dir }}/.Xmodmap"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link
    force: yes

- name: Autostart Xmodmap
  vars:
    user_home: "{{ ansible_facts.user_dir }}"
  template:
    src: "{{ role_path }}/files/xmodmap.desktop.j2"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/xmodmap.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
