---
- name: Austostart Directory
  file:
    path: "{{ ansible_facts.user_dir }}/.config/autostart"
    state: directory

- name: Autostart Redshift - Ubuntu Gnome
  when: ansible_facts.env.DESKTOP_SESSION == "ubuntu"
  copy:
    src: "{{ role_path }}/files/keyboard_caps_is_ctrl.desktop.gnome"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/setxkbmap.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
  
- name: Autostart Redshift - XFCE
  when: ansible_facts.env.DESKTOP_SESSION == "xubuntu"
  copy:
    src: "{{ role_path }}/files/keyboard_caps_is_ctrl.desktop.xfce"
    dest: "{{ ansible_facts.user_dir }}/.config/autostart/setxkbmap.desktop"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
