---
- name: Install tmux - All Ubuntu's
  when: ansible_facts.os_family == "Debian"
  become: yes
  become_method: sudo
  apt:
    pkg:
      - tmux
      - xclip
    state: latest

- name: Install tmux - MacOS
  when: ansible_facts.distribution == "MacOSX"
  homebrew:
    name: tmux
    state: present
    update_homebrew: yes

- name: Symlink main tmux config
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_facts.user_dir }}/.tmux.conf"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link
    force: yes

- name: Symlink tmux Config - MacOS
  when: ansible_facts.distribution == "MacOSX"
  file:
    src: "{{ role_path }}/files/tmux.macos"
    dest: "{{ ansible_facts.user_dir }}/.tmux.macos"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link
    force: yes

- name: Symlink tmux Config - All Ubuntu's
  when: ansible_facts.os_family == "Debian"
  file:
    src: "{{ role_path }}/files/tmux.linux"
    dest: "{{ ansible_facts.user_dir }}/.tmux.linux"
    owner: "{{ ansible_facts.user_id }}"
    group: " {{ ansible_facts.user_gid }}"
    state: link
    force: yes
