- name: Install Docker CLI - MacOS
  when: ansible_facts.distribution == "MacOSX"
  homebrew:
    name: docker
    state: present
    update_homebrew: yes

- name: Install Docker Compose - MacOS
  when: ansible_facts.distribution == "MacOSX"
  homebrew:
    name: docker-compose
    state: present
    update_homebrew: yes

- name: Install Podman - MacOS
  when: ansible_facts.distribution == "MacOSX"
  homebrew:
    name: podman
    state: present
    update_homebrew: yes