#!/usr/bin/env ruby

#
# Removes "_ebook" from the names of all files in DIR
#
# Usage: ruby ./remove_ebook [PATH TO FOLDER]
#
# Examples:
# $ ruby ./remove_ebook.rb /home/user/ebooks
# book_1_ebook.pdf  => book_1.pdf
# book_2_ebook.pdf  => book_2.pdf
#

PHRASE_1 = "_ebook"

SKIP_FILES = [".", ".."]

if ARGV.length != 1
  puts " * * ERROR! * *\n USAGE: ./removeebook.rb [PATH TO FOLDER]"
  exit
end

target_dir = ARGV[0]
files = Dir.entries(target_dir)
cwd = File.absolute_path(target_dir)

files.each do |f|
  next if SKIP_FILES.include?(f)

  new_filename = f.split(PHRASE_1).join()

  old_path = cwd + "/" + f
  new_path = cwd + "/" + new_filename

  File.rename(old_path, new_path)
end
