# File Location: ~/.bash_profile
# Run the following to download and initialize:
# curl -o ~/.bash_profile https://raw.githubusercontent.com/mindovermiles262/scripts/master/bash/bash_profile && source ~/.bash_profile

BASH_PROFILE_URL="https://raw.githubusercontent.com/mindovermiles262/scripts/master/bash/bash_profile"
VIM_RC_URL="https://raw.githubusercontent.com/mindovermiles262/scripts/master/vim/vimrc"

# Load settings from .bashrc
[[ -r ~/.bashrc ]] && . ~/.bashrc


# OS Specific Commands
if [[ "$OSTYPE" == 'linux'* ]]; then
  alias linux-upgrade="sudo apt-get update \
    && sudo apt-get -y upgrade \
    && sudo apt-get -y dist-upgrade \
    && printf 'Linux Has Been Updated\n  {apt-get update}\n  {apt-get upgrade}\n  {apt-get dist-upgrade}\n'"
  alias open="xdg-open ."
elif [[ "$OSTYPE" == "darwin17" ]]; then
  export CLICOLOR=1
  export LSCOLORS=GxFxCxDxBxegedabagaced
fi

# Add color to Terminal:
export PS1="\W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "

# Git branch in terminal.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# File Aliases
alias ll="ls -lha"
alias la="ls -lha"
alias l="ls -lh"

# Add Rails Aliases
alias reset="rails db:migrate:reset; rails db:seed"
alias migrate="rails db:migrate"
alias seed="rails db:seed"

# Editor Aliases
alias v="vim"
alias sv="sudo vim"
alias c="code ."

# Download VIM-Plug and initialize in ~/.vim/autoload, then download .vimrc
alias vim-init="printf 'Downloading Plug\n' \
  && curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
  && curl -o ~/.vimrc $VIM_RC_URL"

# Download and update program profiles
alias vim-update="curl -o ~/.vimrc $VIM_RC_URL"
alias bash-update="curl -o ~/.bash_profile $BASH_PROFILE_URL && source ~/.bash_profile"
alias nord-download="sudo wget -O ~/Documents/nord_ovpn.zip https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip"

# Get current IP address
alias cip="curl https://andyduss.com/ip"

# Search man Pages for flag: 
# USAGE: manf <command> <flag>
function manf () { man $1 | less -p "^ +$2"; }

# Add rbenv to PATH
if [ -d "$HOME/.rbenv" ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# Add asdf to PATH
if [ -d "$HOME/.asdf" ]; then
  . $HOME/.asdf/asdf.sh
  . $HOME/.asdf/completions/asdf.bash
fi
